### ISSUE TITLE
Criar artigo sobre Git

### ISSUE THREAD

**Issue by alexandrevicenzi** [buteco-tech/blog#1]
Criar um artigo explicando Git, GitHub e mostrar os principais comandos como:

- git init
- git pull
- git commit
- git merge
- git remote

Enfim, o usado no dia a dia.

**Comment by LeoDalcegio** [comment]
Opa, eu gostaria de pegar essa Issue pra mim e escrever esse artigo, seria possível?

**Comment by alexandrevicenzi** [comment]
@LeoDalcegio pra agora ou pro hacktoberfest?

**Comment by LeoDalcegio** [comment]
@alexandrevicenzi pro hacktoberfest

**Comment by alexandrevicenzi** [comment]
tranquilo, já está assined pra você

**Comment by LeoDalcegio** [comment]
show, valeu
