### ISSUE TITLE
Adicionar objeto JSON com itens no formato schema.org

### ISSUE THREAD

**Issue by jaswdr** [buteco-tech/blog#11]
Como boa prática de SEO queremos adicionar um objeto JSON a cada página de post usando o formato recomendado pelo [Google Search](https://developers.google.com/search/docs/guides/intro-structured-data)

### Critérios de aceitação
- [ ] Todas as páginas de post's possuem um objeto JSON com informações de título, resumo, tags, categoria, autor e URL

**Comment by alexandrevicenzi** [comment]
Esse erro é meio bizaro, pois tem Schema, na verdade o template usado é [esse](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/schema.html), isso é padrão do Hugo, não sei o que pode estar faltando.

Será que so checam o JSON? Meta tags tbm são aceitas pelo Google.

**Comment by alexandrevicenzi** [comment]
Resolvi no tema, agora inclui um Schema bem completinho pro Google, precisa atualizar a versao no blog ainda pra ter efeito.
