### ISSUE TITLE
Adicionar atributo 'twitter:site' ao card to Twitter

### ISSUE THREAD

**Issue by jaswdr** [buteco-tech/blog#12]
### Critérios de aceitação
- [ ] Todos os cards do Twitter gerados possuem o atribute `twitter:site`

### Links
- [Getting started with Twitter Cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started)
- [Card Validator](https://cards-dev.twitter.com/validator)

**Comment by alexandrevicenzi** [comment]
Isso é config do site, tem que ver certinho como configurar no YAML.

* https://gohugo.io/templates/internal/#twitter-cards
* https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html
