### ISSUE TITLE
Adicionar objeto JSON a página inicial com link para redes sociais usando schema.org

### ISSUE THREAD

**Issue by jaswdr** [buteco-tech/blog#13]
Como boa pratica para melhorar o SEO, queremos adicionar um objeto JSON na página inicial com todas nossas redes sociais usando o formato schema.org.

Exemplo:

```
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Organization",
  "name" : "Example",
 "url" : "https://www.example.com",
 "sameAs" : [
   "https://twitter.com/example",
   "https://www.facebook.com/example",
   "https://foursquare.com/v/example/4e296473149554c77442cc98",
   "http://www.yelp.com/biz/your-business-url-from-yelp", 
   "https://www.instagram.com/example/?hl=en"
   ]
}
</script>
```

Redes sociais:
- [Facebook](https://www.facebook.com/buteco.tech)
- [Twitter](https://twitter.com/butecotech)
- [Instagram](https://www.instagram.com/buteco.tech/)
- [Linkedin](https://www.instagram.com/buteco.tech/)

### Critérios de aceitação
- [x] A página inicial possuí o JSON com link para todas as redes sociais.

**Comment by alexandrevicenzi** [comment]
O Hugo não tem isso, então tem que fuçar no tema ou injetar com header customizado.

Eu particularmente prefiro alterar o tema e configurar no YAML, afinal ja temos as redes sociais configuradas, bastaria ler a config e fazer o same as.

**Comment by alexandrevicenzi** [comment]
Resolvi no tema, agora inclui um Schema bem completinho pro Google, precisa atualizar a versao no blog ainda pra ter efeito.
