### ISSUE TITLE
SEO: Lazy load de imagens

### ISSUE THREAD

**Issue by jaswdr** [buteco-tech/blog#14]
Para otimizar o tempo de carregamento (principalmente mobile) precisamos usar uma estratégia de lazy load para imagens, isso reduzirá o tempo de render, melhorando nosso SEO e experiência do usuário.

### Critérios de aceitação
- [x] Imagens de artigos e página inicial são carregadas após a renderização do HTML

**Comment by alexandrevicenzi** [comment]
Usar a opção de [decoding](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img) será que ajuda?

A maioria dos browsers suporta e da para decodar async, depois de carregar a pagina.

As images no meio de post usam [shortcodes](https://gohugo.io/content-management/shortcodes/), e isso não suporta decode, teria que criar o nosso shortcode que sobrescreve o do Hugo, fácil de fazer.

As imagens do tema teria que setar na unha onde tem tag img, mas eu acho que isso deveria ser customizável.

Tem muito artigo antigo do WP que é HTML puro, mexer nesses é um tiro no pé, melhor deixar pra quando migrar pra Markdown.

Resumindo, essa alteração é um tanto quando complexa.

**Comment by alexandrevicenzi** [comment]
Eu otimizei o tema, é pra estar carregando as imagens de forma asincrona, so quando tu precisar mesmo.

A questao de shortcodes ainda tem que rever, e os posts do WP com html puro nao tem mto o que fazer, mas a home e as paginas é pra estarem otimizadas.
