### ISSUE TITLE
SEO: Minificar arquivos CSS e Javascript

### ISSUE THREAD

**Issue by jaswdr** [buteco-tech/blog#15]
Como boa prática para melhorar o SEO, precisamos diminuir a quantidade de requests e arquivos sendo carregados para renderizar as páginas, uma forma de melhorar isso é minificar os arquivos css e javascript, carregando apenas um único arquivo de cada, respeitando a sequência de dependências.

### Critérios de aceitação
- [ ] Todos os arquivos CSS são minificados em apenas um arquivo, respeitando as dependências entre os arquivos.
- [ ] Todos os arquivos Javascript são minificados em apenas um arquivo, respeitando as dependências entre os arquivos.
- [ ] Os arquivos são (re)minificados ao construir o site usando o comando `hugo`.

**Comment by alexandrevicenzi** [comment]
Isso é algo meio complexo, o tema usa vários plugins, não tem como minificar tudo junto.

O que eu notei é que tem uns items que não estão minificados, isso é alguma coisa zuada no tema provavelmente.

Outra coisa que daria pra fazer é re-minificar no CF, existem umas opções lá que precisam ser analisadas.

Esse tipo de otimização não agrega muito, o site não é lento para carregar, se fosse seria mais ganho.
