### ISSUE TITLE
Compressão de Imagens

### ISSUE THREAD

**Issue by alexandrevicenzi** [buteco-tech/blog#32]
[ImgBot](https://imgbot.net/docs/) é um bot pro Git Hub que pode ajudar a melhorar o site, otimizando e reduzindo tamanho das imagens que usamos.

Uma das reclamações do Google pra mobile é que as imagens são muito grandes e precisam ser otimizadas.

**Comment by alexandrevicenzi** [comment]
@jaswdr o que acha? eu achei interessante, o chato é que ele abre PRs, teria que ficar aceitando, mas podemos ter um workflow que da merge automatico tambem.

**Comment by jaswdr** [comment]
acho uma boa, tenho ele para outros repositórios, e considerando que nós não adicionamos novas imagens com tanta frequência, por mim, acho uma boa sempre revisar as PR's que ele abre para ver se a qualidade das imagens se mantem

**Comment by alexandrevicenzi** [comment]
vou tentar habilitar semana q vem e ver que estrago ele faz :joy:

**Comment by alexandrevicenzi** [comment]
@jaswdr parece que tu ja resolveu com o PR #34, da pra fechar essa issue?

**Comment by jaswdr** [comment]
sim, para novas imagens o ImgBot vai automaticamente abrir PRs se for possível minificar
