### ISSUE TITLE
Criar robots.txt

### ISSUE THREAD

**Issue by jaswdr** [buteco-tech/blog#9]
Uma boa prática para melhorar o SEO do site é criar um arquivo `robots.txt`, este arquivo será lido por bots para determinar qual ou quais páginas o bot deve our pode ler.

### Critérios de aceitação
- [ ] Deve permitir/direcionar para a páginas de [posts](https://butecotecnologico.com.br/posts/)
- [ ] Deve permitir/direcionar para a página do [podcast](https://butecotecnologico.com.br/podcast/)
- [ ] Deve permitir/direcionar para a página de [tags](https://butecotecnologico.com.br/tags/)
- [ ] Deve permitir/direcionar para a página de [categorias](https://butecotecnologico.com.br/categorias/)
- [ ] Deve permitir/direcionar para o XML Sitemap

**Comment by alexandrevicenzi** [comment]
Pode ser * pra tudo, não tem muita coisa pra bloquear eu acho.

**Comment by alexandrevicenzi** [comment]
O hugo tem robots.txt, tem apenas que configurar ele eu acho.
